ARG PYTHON_IMAGE=python:3.11.13-slim
FROM ${PYTHON_IMAGE}

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY pyproject.toml README.md hatch_build.py ./
COPY fhir4ds ./fhir4ds
COPY scripts ./scripts

RUN pip install --upgrade pip \
    && pip install ".[mongo]"

CMD ["python3", "scripts/mongo/smoke_mongo_source.py", "--uri", "mongodb://mongo:27017", "--database", "fhir", "--include-hidden"]
