/**
 * C1-U4b headless parity gate (plan §3.5): the TS envelope builders must
 * produce envelopes identical to the Python operations reference for the
 * §3.8 capability-matrix fixture (fhir4ds/operations/tests/fixtures.py).
 *
 * The Python reference below is generated by the same fixture through
 * fhir4ds.operations.run_tests on desktop DuckDB (normalized per
 * normalized_verify_envelope: timing_ms dropped).
 */
import { describe, expect, it } from "vitest";
import {
  buildEvidenceEnvelope,
  buildVerifyEnvelope,
  type ExecArgs,
  mapColumnTypes,
  namedEvidence,
} from "../../src/lib/executor";
import type { TestCase } from "../../src/lib/protocol";

// --- §3.8 fixture (mirrors fhir4ds/operations/tests/fixtures.py) ---
const MATRIX_OUTPUT_COLUMNS: Record<string, string> = {
  IPP: "Initial Population",
  NAME: "Has Name",
};

const CASES: TestCase[] = [
  { patient: "pt-1", population: "IPP", expect: true },
  { patient: "pt-2", population: "IPP", expect: false },
  { patient: "pt-3", population: "NAME", expect: false },
  { patient: "pt-9", population: "IPP", expect: true },
];

// Population-SQL result rows as duckdb-wasm materializes them
// (plain boolean columns, one row per patient).
const POPULATION_ROWS: Array<Record<string, unknown>> = [
  { patient_id: "pt-1", IPP: true, NAME: true },
  { patient_id: "pt-2", IPP: false, NAME: true },
  { patient_id: "pt-3", IPP: true, NAME: false },
];

// Python reference envelope (normalized): fhir4ds.operations.run_tests on
// the same fixture via desktop DuckDB.
const PYTHON_RUN_TESTS_REFERENCE = {
  schema: 1,
  ok: true,
  passed: false,
  library: "MatrixSimple",
  patients_evaluated: 3,
  summary: { IPP: 2, NAME: 2 },
  tests: {
    total: 4,
    passed: 3,
    failed: 1,
    failures: [
      {
        patient: "pt-9",
        target: "IPP",
        expected: true,
        actual: null,
        reason: "unknown patient: not present in evaluation results",
      },
    ],
  },
};

function verifyArgs(): ExecArgs {
  return {
    capability: "run_tests",
    sql: "",
    column_types: { "Initial Population": "Boolean", "Has Name": "Boolean" },
    tests: { schema: 1, cases: CASES },
    output_columns: MATRIX_OUTPUT_COLUMNS,
  };
}

describe("C1-U4b envelope parity vs Python operations (§3.8 fixture)", () => {
  it("run_tests envelope matches the Python reference field-for-field", () => {
    const env = buildVerifyEnvelope(
      POPULATION_ROWS,
      ["patient_id", "IPP", "NAME"],
      verifyArgs(),
    ) as any;
    // The TS builder emits library: "" (library name lives on the worker
    // layer); normalize exactly like normalized_verify_envelope does for
    // cross-transport library references.
    env.library = "MatrixSimple";
    // timing_ms is volatile — dropped by the shared normalizer.
    delete env.timing_ms;
    expect(env).toEqual(PYTHON_RUN_TESTS_REFERENCE);
  });

  it("summary counts only rows whose column value is strictly true", () => {
    const env = buildVerifyEnvelope(
      POPULATION_ROWS,
      ["patient_id", "IPP", "NAME"],
      verifyArgs(),
    ) as any;
    expect(env.summary).toEqual({ IPP: 2, NAME: 2 });
  });

  it("column_types map through output_columns to CQL types", () => {
    const types = mapColumnTypes(
      { "Initial Population": "Boolean", "Has Name": "Boolean" },
      ["patient_id", "IPP", "NAME"],
      MATRIX_OUTPUT_COLUMNS,
    );
    expect(types).toEqual({ IPP: "Boolean", NAME: "Boolean" });
  });

  it("unknown population column yields a case failure with reason", () => {
    const cases: TestCase[] = [{ patient: "pt-1", population: "NOPE", expect: true }];
    const args = { ...verifyArgs(), tests: { schema: 1, cases } };
    const env = buildVerifyEnvelope(
      POPULATION_ROWS,
      ["patient_id", "IPP", "NAME"],
      args,
    ) as any;
    expect(env.tests.failures[0].reason).toContain("unknown population/define column");
  });
});

describe("C1-U4b explain_patient struct decode parity", () => {
  it("positional audit structs decode to Python named-dict evidence", () => {
    // duckdb-wasm materializes {result, evidence} structs as positional
    // arrays; namedEvidence must restore the Python envelope shape.
    const rows = [
      {
        patient_id: "pt-1",
        IPP: [true, [["Patient/pt-1", null, null, "exists", "[Patient]", ["Initial Population"]]]],
      },
    ];
    const args: ExecArgs = {
      capability: "explain_patient",
      sql: "",
      column_types: {},
      patient_id: "pt-1",
    };
    const env = buildEvidenceEnvelope(rows, ["patient_id", "IPP"], args) as any;
    expect(env.ok).toBe(true);
    expect(env.populations.IPP).toBe(true);
    expect(env.definitions[0].column).toBe("IPP");
    expect(env.definitions[0].evidence[0]).toEqual({
      target: "Patient/pt-1",
      attribute: null,
      value: null,
      operator: "exists",
      threshold: "[Patient]",
      trace: ["Initial Population"],
    });
  });

  it("empty rows produce the not_found diagnostic", () => {
    const args: ExecArgs = {
      capability: "explain_patient",
      sql: "",
      column_types: {},
      patient_id: "zz",
    };
    const env = buildEvidenceEnvelope([], ["patient_id"], args) as any;
    expect(env.ok).toBe(false);
    expect(env.diagnostics[0].code).toBe("not_found");
  });

  it("named-object evidence passes through unchanged", () => {
    const named = {
      target: "Patient/pt-1",
      attribute: null,
      value: null,
      operator: "exists",
      threshold: "[Patient]",
      trace: ["Initial Population"],
    };
    expect(namedEvidence(named)).toEqual(named);
  });
});
