ARG PYTHON_IMAGE=python:3.11.13-slim
FROM ${PYTHON_IMAGE}

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY pyproject.toml README.md hatch_build.py ./
COPY fhir4ds ./fhir4ds

RUN pip install --upgrade pip \
    && pip install ".[hapi]"

ENTRYPOINT ["fhir4ds", "dqm", "hapi"]
CMD ["listen", "--config", "/config/hapi-materialization.yaml"]
