"""Audit engine — relevance-prune evidence per population persona."""

from __future__ import annotations

from .types import AuditOrStrategy, AuditPersona, PopulationMap  # noqa: F401


class AuditEngine:
    """Relevance-prune evidence per population persona."""

    RELEVANCE_STRATEGIES = {
        AuditPersona.INCLUSION: "always",
        AuditPersona.EXCLUSION: "only_when_excluded",
        AuditPersona.NUMERATOR: "always",
    }

    def prune_evidence(
        self, row: dict, population_code: str, persona: AuditPersona
    ) -> list[dict]:
        """Prune evidence based on the population persona.

        For exclusion populations, evidence is only relevant when the patient
        IS excluded (i.e., the exclusion criterion is True). When the patient
        is NOT excluded, the exclusion evidence is irrelevant.
        """
        col_key = population_code.replace("-", "_")
        pop_value = row.get(col_key)

        # Extract evidence from struct if present
        if isinstance(pop_value, dict):
            evidence = pop_value.get("evidence", [])
            is_satisfied = pop_value.get("result", False)
        else:
            evidence = []
            is_satisfied = bool(pop_value)

        if not evidence:
            return []

        strategy = self.RELEVANCE_STRATEGIES.get(persona, "always")
        if strategy == "only_when_excluded" and not is_satisfied:
            return []

        # Compact the flat evidence list generated by SQL into grouped findings
        return self._compact_evidence(evidence)

    def _compact_evidence(self, flat_evidence: list[dict]) -> list[dict]:
        """Group flat evidence items by trace, attribute, operator, and threshold."""
        compacted = {}
        for item in flat_evidence:
            if not isinstance(item, dict):
                continue
            trace = tuple(item.get("trace", []))
            attr = item.get("attribute")
            op = item.get("operator")
            thresh = item.get("threshold")

            group_key = (trace, attr, op, thresh)
            if group_key not in compacted:
                compacted[group_key] = {
                    "trace": list(trace),
                    "attribute": attr,
                    "operator": op,
                    "threshold": thresh,
                    "findings": []
                }

            # Avoid duplicate targets within the same finding group
            target = item.get("target")
            val = item.get("value")
            finding = {"target": target}
            if val is not None:
                finding["value"] = val

            if finding not in compacted[group_key]["findings"]:
                compacted[group_key]["findings"].append(finding)

        return list(compacted.values())
